# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo $(SYSTEM.PULLREQUEST.SOURCEBRANCH)
    echo $(Build.SourceBranch)
    echo $(Build.SourceBranchName)
    echo $(System.PullRequest.IsFork)
    echo $(System.PullRequest.targetBranchName)
    echo $(System.PullRequest.TargetBranch)
    git log
    git status
    git branch
    git fetch origin pull/$(SYSTEM_PULLREQUEST_PULLREQUESTNUMBER)/head:$(Build.SourceBranch);
    git --no-pager diff --name-only --merge-base origin/$(System.PullRequest.TargetBranch) $(Build.SourceBranch)
  displayName: 'Run a multi-line script'
