# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo $(SYSTEM.PULLREQUEST.SOURCEBRANCH)
    echo $(Build.SourceBranch)
    echo $(Build.SourceBranchName)
    echo $(System.PullRequest.IsFork)
    echo $(System.PullRequest.targetBranchName)
    echo $(System.PullRequest.TargetBranch)
    git log
    git status
    git branch
    echo == 1 ==
    git fetch origin pull/$(SYSTEM.PULLREQUEST.PULLREQUESTNUMBER)/head:$(SYSTEM.PULLREQUEST.SOURCEBRANCH)
    echo == 2 ==
    baseCommit=git --merge-base $(SYSTEM.PULLREQUEST.SOURCEBRANCH) origin/$(System.PullRequest.TargetBranch)
    echo == 3 ==
    echo $baseCommit
    echo == 4 ==
    git --no-pager diff --name-only $baseCommit $(SYSTEM.PULLREQUEST.SOURCEBRANCH)
  displayName: 'Run a multi-line script'
